/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#003543",
        "on-tertiary-container": "#694a82",
        "primary-fixed-dim": "#4ce085",
        "on-secondary-fixed-variant": "#004e60",
        "on-secondary-container": "#00566a",
        "surface-container-lowest": "#0e0e0e",
        "secondary-container": "#00d2ff",
        "on-surface": "#e5e2e1",
        "tertiary-container": "#e4bfff",
        "on-error": "#690005",
        "surface-bright": "#3a3939",
        "background": "#131313",
        "surface-container-highest": "#353534",
        "on-primary-fixed": "#00210d",
        "surface-dim": "#131313",
        "on-primary-container": "#006433",
        "tertiary-fixed-dim": "#deb8f9",
        "tertiary-fixed": "#f2daff",
        "primary": "#98ffb4",
        "on-background": "#e5e2e1",
        "surface-tint": "#4ce085",
        "inverse-surface": "#e5e2e1",
        "secondary-fixed-dim": "#47d6ff",
        "inverse-primary": "#006d38",
        "on-tertiary": "#402358",
        "primary-fixed": "#6dfe9f",
        "secondary": "#a5e7ff",
        "on-primary": "#00391a",
        "surface-container-low": "#1c1b1b",
        "inverse-on-surface": "#313030",
        "error-container": "#93000a",
        "tertiary": "#f6e3ff",
        "surface-container": "#201f1f",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#005228",
        "surface-container-high": "#2a2a2a",
        "on-surface-variant": "#bccabb",
        "surface-variant": "#353534",
        "on-tertiary-fixed-variant": "#583a70",
        "primary-container": "#54e78b",
        "surface": "#131313",
        "outline": "#869486",
        "on-secondary-fixed": "#001f28",
        "on-tertiary-fixed": "#2a0b42",
        "outline-variant": "#3d4a3e",
        "error": "#ffb4ab",
        "secondary-fixed": "#b6ebff"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        glow: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(84, 231, 139, 0.3)' },
          '50%': { boxShadow: '0 0 40px rgba(84, 231, 139, 0.6)' },
        },
        slideUp: {
          'from': { opacity: '0', transform: 'translateY(20px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        slideIn: {
          'from': { opacity: '0', transform: 'translateX(-20px)' },
          'to': { opacity: '1', transform: 'translateX(0)' },
        },
      },
      animation: {
        float: 'float 6s ease-in-out infinite',
        glow: 'glow 2s ease-in-out infinite',
        slideUp: 'slideUp 0.6s ease-out',
        slideIn: 'slideIn 0.6s ease-out',
      },
    },
  },
  plugins: [],
}
